name: ballots_template_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dio: ^5.6.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image_gallery_saver: ^2.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  printing: ^5.13.2
  share_plus: ^10.0.2
  signature: ^5.5.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  launcher_name: ^1.0.2
  
launcher_name:
  default: "Receipt\nGenerator"
  es: "Generador de\nRecibos" 

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/gifs/