name: ballots_template_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  signature: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  launcher_name: ^1.0.2
  
launcher_name:
  default: "Receipt\nGenerator"
  es: "Generador de\nRecibos" 

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/